name: waserver builder 

on: [push, pull_request]

env:
  VERSION: 1.0.0.${{github.run_number}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Check Environment
      run: |
        ls
        echo $NOW
        echo $VERSION
        echo $GITHUB_SHA

    - name: Test
      run: |
        go test -cover

    - name: Linux PC/x64 build and zip
      run: |
        go build -v -ldflags="-X 'main.applicationBuildTime=$NOW' -X main.applicationVersion=$VERSION -X main.applicationGitHash=$GITHUB_SHA" ./...
        tar -zcvf waserver_linux_x64.tar.gz  waserver app/

    - name: Linux ARM (cross compile from linux x64)
      run: |
        rm waserver
        export GOOS=linux 
        export GOARCH=arm
        export GOARM=5
        go build -v -ldflags="-X 'main.applicationBuildTime=$NOW' -X main.applicationVersion=$VERSION -X main.applicationGitHash=$GITHUB_SHA" ./...
        tar -zcvf waserver_linux_arm.tar.gz  waserver app/

    - name: Create Tag
      uses: rickstaa/action-create-tag@v1.7.2
      if: github.ref == 'refs/heads/main'
      with:
        tag: waserver-v${{env.VERSION}}

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        name: waserver-v${{env.VERSION}}
        tag_name: waserver-v${{env.VERSION}}
        files: |
          waserver_linux_x64.tar.gz
          waserver_linux_arm.tar.gz


